version: "3.8"

services:
  backend:
    image: sangkong12/backend:1.0
    container_name: backend
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    image: sangkong12/frontend:5.0
    container_name: frontend
    ports:
      - "80:80"   # 👈 QUAN TRỌNG
    depends_on:
      - backend   # 👈 nên có
    networks:
      - app-network

networks:
  app-network: